
["Integrated Minecraft"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["Integrated Minecraft".General]
		# Whether or not Integrated Minecraft disables some structures.
		# Default: true
		#
		"Disable Structures" = true

["Perk Settings"]
	#Settings related to Ars Nouveau perk integration
	#List of armor registry names that should get thread slots
	perk_armors = ["minecraft:netherite_chestplate", "minecraft:netherite_leggings"]

