#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 29 23:34:30 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=ComplementaryReimagined_r5.4.zip
enableShaders=false
